### ISSUE TITLE
Warp-Companion repository

### ISSUE THREAD

**Issue by rosslh** [trbndev/trbn.dev#1]
Hey Torben, I hope you're doing well! Sorry for contacting you via this GitHub issue but I wasn't sure how else to reach you. I noticed the GitHub repository for Warp-Companion no longer exists publicly. I was wondering if that was intentional? I really like the extension and would hate to see it disappear. Thanks.

**Comment by trbndev** [comment]
Hi! I archived and made it private, since I've switched to Windows some time ago. 

Love to see though, that there's still some people using it. Just made the repo public again.

Maybe I'll try to tinker around with Warp on WSL and give some updates to the extension 😀 

https://github.com/trbndev/warp-companion
